name:                autocomplete-haskell
version:             0.1.0.0
github:              "wannabesmith/autocomplete-haskell"
license:             BSD3
author:              "Ian Waudby-Smith"
maintainer:          "iwaudbysmith@gmail.com"
copyright:           "2019 Ian Waudby-Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An autocomplete implementation along with functions for working with tries.

dependencies:
- base >= 4.7 && < 5
- containers
- heap
- filepath
- hspec
- text
- criterion
- unordered-containers
- deepseq
- min-max-pqueue

library:
  source-dirs: src

executables:
  autocomplete-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autocomplete-haskell

tests:
  autocomplete-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autocomplete-haskell
